// packages/vendure-plugin-order-export/src/dashboard/components/OrderExport.tsx
import {
  api,
  Button,
  DateRangePicker,
  DefinedDateRange,
  Label,
  LS_KEY_SELECTED_CHANNEL_TOKEN,
  LS_KEY_SESSION_TOKEN,
  Page,
  PageBlock,
  PageLayout,
  PageTitle,
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@vendure/dashboard';
import { graphql } from '@/gql';
import { getApiBaseUrl } from '@/vdb/utils/config-utils.js';
import { useQuery } from '@tanstack/react-query';
import { endOfDay, startOfMonth } from 'date-fns';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';

const StrategiesQuery = graphql(`
  query availableOrderExportStrategies {
    availableOrderExportStrategies
  }
`);

export function OrderExportComponent() {
  const [dateRange, setDateRange] = useState<DefinedDateRange>({
    from: startOfMonth(new Date()),
    to: endOfDay(new Date()),
  });
  const [strategy, setStrategy] = useState('');
  const [isDownloading, setIsDownloading] = useState(false);

  const { data } = useQuery({
    queryKey: ['availableOrderExportStrategies'],
    queryFn: () => api.query(StrategiesQuery),
  });
  const strategies = data?.availableOrderExportStrategies ?? [];

  useEffect(() => {
    if (strategies.length && !strategy) {
      setStrategy(strategies[0]);
    }
  }, [strategies]);

  async function handleDownload() {
    setIsDownloading(true);
    try {
      const headers: Record<string, string> = {};
      const channelToken = localStorage.getItem(LS_KEY_SELECTED_CHANNEL_TOKEN);
      if (channelToken) headers['vendure-token'] = channelToken;
      const sessionToken = localStorage.getItem(LS_KEY_SESSION_TOKEN);
      if (sessionToken) headers['Authorization'] = `Bearer ${sessionToken}`;

      const url =
        `${getApiBaseUrl()}/export-orders/export/${strategy}` +
        `?startDate=${dateRange.from.toISOString()}&endDate=${dateRange.to.toISOString()}`;

      const res = await fetch(url, { credentials: 'include', headers });
      if (!res.ok) {
        const json = await res.json();
        throw new Error(json?.message);
      }
      const contentDisposition = res.headers.get('Content-Disposition') ?? '';
      const filename =
        contentDisposition.split(';')[1]?.split('=')?.[1] ?? 'export';
      const blobUrl = window.URL.createObjectURL(await res.blob());
      const a = Object.assign(document.createElement('a'), {
        href: blobUrl,
        download: filename,
      });
      a.click();
      window.URL.revokeObjectURL(blobUrl);
    } catch (err: any) {
      toast.error(err.message ?? 'Export failed');
    } finally {
      setIsDownloading(false);
    }
  }

  return (
    <Page pageId="order-export">
      <PageTitle>Export orders</PageTitle>
      <PageLayout>
        <PageBlock column="main" blockId="export-form">
          <div className="space-y-6">
            <div className="space-y-2">
              <Label>Date range</Label>
              <DateRangePicker
                dateRange={dateRange}
                onDateRangeChange={setDateRange}
              />
            </div>
            <div className="space-y-2">
              <Label>Export as</Label>
              <Select value={strategy} onValueChange={setStrategy}>
                <SelectTrigger className="w-[240px]">
                  <SelectValue placeholder="Select a strategy" />
                </SelectTrigger>
                <SelectContent>
                  {strategies.map((s) => (
                    <SelectItem key={s} value={s}>
                      {s}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <Button
              onClick={handleDownload}
              disabled={!strategy || isDownloading}
            >
              {isDownloading ? 'Exporting...' : 'Export'}
            </Button>
          </div>
        </PageBlock>
      </PageLayout>
    </Page>
  );
}

// packages/vendure-plugin-order-export/src/ui/order-export.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import {
  DataService,
  getServerLocation,
  LocalStorageService,
  NotificationService,
} from '@vendure/admin-ui/core';
import gql from 'graphql-tag';

@Component({
  standalone: false,
  encapsulation: ViewEncapsulation.None, // Hide time picker on children of order export
  selector: 'order-export-component',
  styles: ['.time-picker { display: none !important; }'],
  template: `
    <div class="page-block">
      <h1 class="mb-2">Export orders</h1>
      <form class="form" [formGroup]="form" id="export-form">
        <section class="form-block">
          <div class="flex">
            <div>
              <label>{{ 'common.start-date' | translate }}</label>
              <vdr-datetime-picker
                required
                timeGranularityInterval="60"
                formControlName="startsAt"
              ></vdr-datetime-picker>
            </div>
            <div>
              <label>{{ 'common.end-date' | translate }}</label>
              <vdr-datetime-picker
                required
                timeGranularityInterval="60"
                formControlName="endsAt"
              ></vdr-datetime-picker>
            </div>
          </div>
          <br />
          <clr-select-container>
            <label>Export as</label>
            <select
              clrSelect
              name="options"
              formControlName="strategy"
              required
            >
              <option *ngFor="let strategy of strategies" [value]="strategy">
                {{ strategy }}
              </option>
            </select>
          </clr-select-container>
          <br />
          <button
            class="btn btn-primary"
            [disabled]="form.invalid || form.pristine"
            (click)="download()"
          >
            Export
          </button>
        </section>
      </form>
    </div>
  `,
})
export class OrderExportComponent implements OnInit {
  form: FormGroup;
  serverPath: string;
  strategies: string[] = [];

  constructor(
    private formBuilder: FormBuilder,
    protected dataService: DataService,
    private notificationService: NotificationService,
    private localStorageService: LocalStorageService
  ) {
    this.form = this.formBuilder.group({
      startsAt: null,
      endsAt: null,
      strategy: null,
    });
    this.serverPath = getServerLocation();
  }

  ngOnInit(): void {
    this.dataService
      .query(
        gql`
          query availableOrderExportStrategies {
            availableOrderExportStrategies
          }
        `
      )
      .single$.subscribe((result: any) => {
        this.strategies = result.availableOrderExportStrategies;
        this.form.controls['strategy'].setValue(this.strategies?.[0]);
      });
  }

  async download(): Promise<void> {
    try {
      const res = await fetch(
        `${this.serverPath}/export-orders/export/${this.form.value.strategy}?startDate=${this.form.value.startsAt}&endDate=${this.form.value.endsAt}`,
        {
          headers: this.getHeaders(),
        }
      );
      if (!res.ok) {
        const json = await res.json();
        throw Error(json?.message);
      }
      const header = res.headers.get('Content-Disposition');
      const parts = header!.split(';');
      const filename = parts[1].split('=')[1];
      const blob = await res.blob();
      await this.downloadBlob(blob, filename);
    } catch (err: any) {
      console.error(err);
      this.notificationService.error(err.message);
    }
  }

  private getHeaders(): Record<string, string> {
    const headers: Record<string, string> = {};
    const channelToken = this.localStorageService.get('activeChannelToken');
    if (channelToken) {
      headers['vendure-token'] = channelToken;
    }
    const authToken = this.localStorageService.get('authToken');
    if (authToken) {
      headers.authorization = `Bearer ${authToken}`;
    }
    return headers;
  }

  private async downloadBlob(blob: Blob, fileName: string): Promise<void> {
    const blobUrl = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    document.body.appendChild(a);
    a.setAttribute('hidden', 'true');
    a.href = blobUrl;
    a.download = fileName;
    a.setAttribute('target', '_blank');
    a.click();
  }
}
